[tool.mypy]
install_types = true
non_interactive = true
strict = true
disallow_untyped_defs = true
ignore_missing_imports = true

[tool.flake8]
max-line-length = 140
ignore = ["D100", "D101", "D102", "D103", "D104", "D107", "R504"]
exclude = [".git", "__pycache__", ".vevn"]
max-complexity = 8
per-file-ignores = [
    '__init__.py:F401',
]

[tool.black]
line-length = 140

[tool.isort]
py_version = 39
line_length = 140