name: base
channels:
- conda-forge
- pytorch
- nvidia
dependencies:
- flake8-pyproject==1.2.3
- numpy==1.26.2
- opencv==4.8.1
- pytorch==2.1.1
- pytorch-cuda=11.8
- streamlit==1.29.0
- torchvision==0.16.1
- yaml==0.2.5
